[package]
name = "aura-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aura-actor = { path = "../actor" }
aura-realm = { path = "../realm" }
aura-storage = { path = "../storage" }
aura-config = { path = "../config" }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tempfile = "3"

[features]
default = []
steel = ["aura-realm/steel"]
python = ["aura-realm/python"]
wasmtime = ["aura-realm/wasmtime"]
nushell = ["aura-realm/nushell"]
fjall = ["aura-storage/fjall"]
